import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import AppProvider from "./components/AppProvider";
import  { Toaster } from 'react-hot-toast';
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });
import Footer from '@/app/components/layout/Footer'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
    <head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
    </head>
      <body className={roboto.className}>
        <main className="w-full  mx-auto">
          <AppProvider>
            <Header />
            {children}
          </AppProvider>
            <Toaster/>
        </main>
        <footer className="border-t w-full mt-5">
              <p className=" text-gray-500 text-center py-4">
                {" "}
                &copy; 2024 All rights are reserved
              </p>
            </footer>

      </body>
    </html>
  );
}
