import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import AppProvider from "./components/AppProvider";
import  { Toaster } from 'react-hot-toast';
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl p-4 mx-auto">
          <AppProvider>
            <Header />
            {children}
            <footer className="mt-8 border-t w-full">
              <p className=" text-gray-500 text-center py-4">
                {" "}
                &copy; 2024 All rights are reserved
              </p>
            </footer>
          </AppProvider>
            <Toaster/>
        </main>
      </body>
    </html>
  );
}
